version: "3.3"
services:
  database:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=wager
      - POSTGRES_PASSWORD=wager
      - POSTGRES_DB=wager
    ports:
      - 6000:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
    volumes:
      - database-data:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://wager:wager@database/wager
      WAGER_SECRET: asdfasdf
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '2'
    ports:
      - 8080:8080
volumes:
  database-data:

    # psql --host=database --username=wager --dbname=wager

    # DATABASE_URL=postgres://wager:wager@0.0.0.0:6000/wager