version: "3.3"
services:
  database:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
      - POSTGRES_DB=users
    ports:
      - 6000:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
    volumes:
      - database-data:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://users:users@database/users
      WAGER_SECRET: asdfasdf
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '2'
    ports:
      - 8080:8080
volumes:
  database-data:

    # psql --host=database --username=users --dbname=users

    # export DATABASE_URL=postgres://users:users@0.0.0.0:6000/users

    # export USERS_SECRET=my_secret
